### ISSUE TITLE
Docstrings ending in a double quote break generated code

### ISSUE THREAD

**Issue by JacekLach** [palantir/conjure-python#165]
conjure-python will happily generate

```
def foo(self):
    # type: () -> Optional[str]
    """Foo: returns the string "bar""""
    ...
```

when given the doc string of `Foo: returns the string "bar"`

**Comment by iamdanfox** [comment]
@JacekLach what would be preferred here? does multiline work?
```python
def foo(self):
    # type: () -> Optional[str]
    """
    Foo: returns the string "bar"
    """
    ...
```

**Comment by JacekLach** [comment]
yeah I think just injecting a newline before/after the docstring should fix it

**Comment by ahggns** [comment]
#138 did this, and #225 does some more
