### ISSUE TITLE
Query params are not serialized according to the conjure wire spec

### ISSUE THREAD

**Issue by afloren** [palantir/conjure-python#340]
## What happened?

Attempted to call a service with a conjure-python generated client, where the endpoint defined a query param of type `list<string>`. The service failed to deserialize the query param because it passed the list raw, i.e., `param=[value1, value2]`

## What did you want to happen?

Generated clients should serialize query params according to the conjure wire spec https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#22-query-parameters so that services deserialize properly, i.e., `param=value1&param=value2`

**Comment by AaronJRubin** [comment]
This is fixed in https://github.com/palantir/conjure-python-client/pull/101

**Comment by afloren** [comment]
amazing cheers!
