### ISSUE TITLE
Path parameters are not url encoded

### ISSUE THREAD

**Issue by ktekelioglu** [palantir/conjure-python#595]
## What happened?

This was discovered in the palantir-python-sdk library: https://github.com/palantir/palantir-python-sdk/issues/20

Python classes generated by this library have a bug when a special character is encountered in a path parameter. The example in the above issue is a branch parameter with a '/' character.

## What did you want to happen?

Path parameters should be url encoded. It can be done with a simple utility function as such:

```
def format_path_with_params(path, path_params):
    escaped_path_params = {
        k: requests.utils.quote(v, safe="") for k, v in path_params.items()
    }
    return path.format(**escaped_path_params)
```

**Comment by BenjaminLowry** [comment]
Addressed in https://github.com/palantir/conjure-python/pull/927
