### ISSUE TITLE
Union type with name of "property" fails at runtime

### ISSUE THREAD

**Issue by vipshek** [palantir/conjure-python#70]
## What happened?

If I define a union type like so:
```
MyType:
  union:
    property: TypeA
    otherType: TypeB
```

When attempting to import this union type, I get a failure traceback like this:
```
Traceback (most recent call last):
  File "...", line N, in <module>
    from my_package import MyType
  File "...", line N, in <module>
    class MyType(ConjureUnionType):
  File "...", line N, in MyType
    @property
TypeError: 'property' object is not callable
```

where the failure references the `@property` annotation on the `other_type` function in the generated `MyType` class:

```
    @property
    def property(self):
        # type: () -> TypeA
        return self._property

--> @property
    def other_type(self):
        # type: () -> TypeB
        return self._other_type
```

## What did you want to happen?

Either generating this union type should fail during Conjure compilation, or there should be some variant of this generated that prevents the issue, such as naming the generated function `_property` instead.

**Comment by iamdanfox** [comment]
Fixed in #76
