### ISSUE TITLE
Using the name of a builtin as a property (like "property") breaks the generated code

### ISSUE THREAD

**Issue by martijnarts** [palantir/conjure-python#74]
It generates this:

```python
    @property
    def property(self):
        # type: () -> str
        """Bar foo"""
        return self._property

    @property
    def second_thing(self):
        # type: () -> str
        """Foo bar"""
        return self._second_thing
```

Which breaks on line 7, when it tries to use the earlier method called `property` as a decorator.

It should probably `import __builtin__` at the start and use `@__builtin__.property` instead. The same would be true for other builtins.

**Comment by iamdanfox** [comment]
@TotempaaltJ could you try upgrading to latest (3.11.0)? #76 should fix this.
