### ISSUE TITLE
Enum path parameters serialized incorrectly

### ISSUE THREAD

**Issue by jawshooah** [palantir/conjure-python#925]
[Path parameters](https://palantir.github.io/conjure/#/docs/spec/wire?id=_21-path-parameters) that are [enum types](https://palantir.github.io/conjure/#/docs/spec/conjure_definitions?id=enumtypedefinition) are serialized as `EnumType.VALUE` in the request path instead of just `VALUE`.

**Comment by BenjaminLowry** [comment]
Addressed in https://github.com/palantir/conjure-python/pull/927
